# Generated by Django 3.2.8 on 2021-12-03 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='slug',
            field=models.SlugField(default='empty', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='email_1',
            field=models.EmailField(max_length=254, verbose_name='Email 1'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email_2',
            field=models.EmailField(max_length=254, verbose_name='Email 2'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='position',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('sales', 'Sales'), ('service', 'Service'), ('accounting', 'Accounting'), ('executive', 'Executive'), ('product development', 'Product Development'), ('marketing', 'Marketing'), ('logistics', 'Logistics'), ('purchasing', 'Purchasing'), ('IT', 'IT')], max_length=25, verbose_name='Position or Role'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='billing_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_billing', to='customer.address', verbose_name='Billing Address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='shipping_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_location', to='customer.address', verbose_name='Shipping Address'),
        ),
    ]
