# Generated by Django 3.2.8 on 2021-12-03 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20211203_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='active',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], max_length=25, verbose_name='Activate Account'),
        ),
    ]
