# Generated by Django 3.2.8 on 2021-12-03 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_address_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='role',
            field=models.CharField(choices=[('both', 'Billing/Shipping'), ('shipping', 'Shipping Address'), ('billing', 'Billing Address')], max_length=10, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_location', to='customer.address', verbose_name='Shipping Address'),
        ),
    ]
