# Generated by Django 3.2.8 on 2021-12-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20211203_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='active',
            field=models.CharField(choices=[('active', 'Active'), ('active', 'Inactive'), ('active', 'Archived')], max_length=25, verbose_name='Activate Account'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='active',
            field=models.CharField(choices=[('active', 'Active'), ('active', 'Inactive'), ('active', 'Archived')], max_length=25, verbose_name='Active'),
        ),
    ]
