# Generated by Django 3.2.8 on 2021-12-03 05:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20211203_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Address 2'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email_1',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email 1'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email_2',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email 2'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_1',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^(\\d{10}$)', 'Please use numerical format without any spaces or special characters')], verbose_name='Phone 1'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_2',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^(\\d{10}$)', 'Please use numerical format without any spaces or special characters')], verbose_name='Phone 2'),
        ),
    ]
